// Define the media types
export interface MediaItem {
    id: number;
    title: string;
    description: string;
    source: string;
    type: "image" | "video";
    thumbnail?: string;
    category: string;
}

// Import your image assets (these imports would match your project structure)
// Note: You'll need to import all your assets here
import welderHero from "../assets/welderHero.jpg";
import welderHero2 from "../assets/welderHero2.jpg";
import plumperHero from "../assets/plumperHero.jpg";
import fm200BF from "../assets/fm200BF.jpg";
import fm200Hero from "../assets/fm200Hero.jpg";

// Sample media items
export const mediaItems: MediaItem[] = [
    {
        id: 1,
        title: "Welding and Fabrication",
        description: "Professional Welding & Fabrication",
        source: welderHero,
        type: "image",
        category: "Welding",
    },
    {
        id: 2,
        title: "FM200 Installation",
        description: "FM200 fire suppression system installation process",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938448/IMG_20250111_074505_ftltre.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 3,
        title: "FM200 Completion",
        description: "Completed FM200 installation in a server room",
        source: fm200Hero,
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 4,
        title: "Fire safety equipment",
        description: "Modern equipment and certified technicians for your protection",
        source: welderHero2,
        type: "image",
        category: "Welding",
    },
    {
        id: 5,
        title: "FM200 Fire Suppression System Installation",
        description: "FM200 fire suppression system installation process",
        source: "https://res.cloudinary.com/dn52re1os/video/upload/v1746516862/fm200fit_rbyimu.mp4",
        type: "video",
        thumbnail: "https://res.cloudinary.com/dn52re1os/image/upload/v1746519385/Screenshot_2025-05-06_091249_o6t9im.png",
        category: "Fire Alarm",
    },
    {
        id: 6,
        title: "Piping and Fitting",
        description: "Reliable installation and maintenance services",
        source: plumperHero,
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 7,
        title: "Piping Installation",
        description: "Professional pipe installation services",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934877/IMG-20250429-WA0053_uk6feu.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 8,
        title: "FM200 Fire Suppression System Installation Highlights",
        description: "highlights of the FM200 fire suppression system installation process",
        source: "https://res.cloudinary.com/dn52re1os/video/upload/v1746516860/fm200fit2_bhijq2.mp4",
        type: "video",
        thumbnail: "https://res.cloudinary.com/dn52re1os/image/upload/v1746519383/Screenshot_2025-05-06_091356_y1m8gs.png",
        category: "Fabrication",
    },
    {
        id: 9,
        title: "FM200 Fire Suppression Systems",
        description: "Custom fabricated pipe fitting for fire suppression systems",
        source: fm200BF,
        type: "image",
        category: "FM200 Installation",
    },
    // Add more media items below as needed
    {
        id: 10,
        title: "Piping and Sprinkler Installation",
        description: "Pipe and sprinkler installation",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934878/IMG-20250429-WA0058_xg3otk.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 11,
        title: "Welding Pipe Systems",
        description: "highlights of welding pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/video/upload/v1746516861/powerBuildingWelding_rdcwwa.mp4",
        type: "video",
        thumbnail: "https://res.cloudinary.com/dn52re1os/image/upload/v1746520215/Screenshot_2025-05-06_092821_avgayl.png",
        category: "Fabrication",
    },
    {
        id: 12,
        title: "Water Tank System Installation",
        description: "Water tank installation and piping setup",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934877/IMG-20250429-WA0054_zawr0s.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 13,
        title: "Metal Fabrication",
        description: "Custom metal work for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934875/IMG-20250429-WA0047_wjgvsi.jpg",
        type: "image",
        category: "Fabrication",
    },
    {
        id: 14,
        title: "Metalwork Fabrication",
        description: "Custom metal work for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934874/IMG-20250429-WA0042_wcoqim.jpg",
        type: "image",
        category: "Fabrication",
    },
    {
        id: 15,
        title: "Industrial Piping",
        //  omolayo awoyinka ewaoluwa oluwatoyosi oluwaferanmijuomogbogboarayelo
        description: "Complex industrial piping system installation",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934867/IMG-20250429-WA0011_yslkoa.jpg",
        type: "image",
        category: "Piping and Fitting",
    },

    {
        id: 16,
        title: "Industrial Pipe Systems Installation Highlights",
        description: "Highlights of pipe systems installation process",
        source: "https://res.cloudinary.com/dn52re1os/video/upload/v1746516873/powerBuildingPipes_p0luod.mp4",
        type: "video",
        thumbnail: "https://res.cloudinary.com/dn52re1os/image/upload/v1746520862/Screenshot_2025-05-06_094034_u2pt1n.png",
        category: "Fabrication",
    },
    {
        id: 17,
        title: "Fire Extinguisher",
        description: "Demonstration of precision welding methods",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934876/IMG-20250429-WA0048_tpcx41.jpg",
        type: "image",
        category: "Fire Extinguisher",
    },
    {
        id: 18,
        title: "Emergency Systems",
        description: "Fire Extinguisher",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934868/IMG-20250429-WA0016_qklzjd.jpg",
        type: "image",
        category: "Fire Extinguisher",
    },
    {
        id: 19,
        title: "Fire Extinguisher",
        description: "Artistic metal fabrication for decorative elements",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934867/IMG-20250429-WA0008_oegvly.jpg",
        type: "image",
        category: "Fire Extinguisher",
    },
    // You can add more items as needed
    {
        id: 20,
        title: "Fabrication",
        description: "Metal fabrication for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938740/IMG_20250115_070608_kkg9tv.jpg",
        type: "image",
        category: "Fabrication",
    },
    {
        id: 21,
        title: "Pipe Systems Installation",
        description: "Metal fabrication for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938989/IMG_20250206_100941_mcwb0v.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 22,
        title: "Pipe Systems Installation",
        description: "Metal fabrication for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745939010/IMG_20250206_081241_gjufoa.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 23,
        title: "Pipe Systems Installation",
        description: "Custom metal work for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938997/IMG_20250203_110423_lb7ccy.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 24,
        title: "Metalwork Fabrication",
        description: "Custom metal work for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745939002/IMG_20250204_091246_nldtzq.jpg",
        type: "image",
        category: "Fabrication",
    },
    {
        id: 25,
        title: "Welding and Fabrication",
        //  omolayo awoyinka ewaoluwa oluwatoyosi oluwaferanmijuomogbogboarayelo
        description: "Complex industrial piping system installation",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938742/IMG_20250116_040205_eora3j.jpg",
        type: "image",
        category: "Fabrication",
    },
    {
        id: 26,
        title: "Industrial Piping",
        description: "Complex industrial piping system installation",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938124/IMG_20250326_062139_rrlclq.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 27,
        title: "FM200 Pipe Systems Installation",
        description: "Demonstration of precision extinguishers",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938128/IMG_20250326_062152_vbwgtw.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 28,
        title: "Emergency Systems",
        description: "FM200 fire suppression system installation process",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938121/IMG_20250326_062127_sm0xew.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 29,
        title: "Fire Extinguisher",
        description: "FM200 Fire Suppression Cylinders",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938106/IMG_20250326_061905_ajwyzt.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    // You can add more items as needed
    {
        id: 30,
        title: "FM200 Pipe Systems Installation",
        description: "Metal fabrication for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938117/IMG_20250326_061957_ifjtl0.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 31,
        title: "Pipe Installation NCAA",
        description: "Professional fire alarm system setup",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934878/IMG-20250429-WA0057_m8ewzt.jpg",
        type: "image",
        category: "Fire Alarm",
    },
    {
        id: 32,
        title: "FM200 Pipe Systems Installation",
        description: "Metal fabrication for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938435/IMG_20250110_083500_j7xhwu.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 33,
        title: "Pipe Systems Installation",
        description: "Bolting together FM200 nozzle and pipe system",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938441/IMG_20250111_052407_po9cw6.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 34,
        title: "Inspection of FM200 Pipe Systems",
        description: "Custom metal work for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934874/IMG-20250429-WA0043_izftrz.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 35,
        title: "Pressure Testing FM200 Fire Suppression System",
        //  omolayo awoyinka ewaoluwa oluwatoyosi oluwaferanmijuomogbogboarayelo
        description: "Pressure testing FM200 pipe system with nitrogen gas",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934874/IMG-20250429-WA0041_h9wjw7.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 36,
        title: "Industrial Piping",
        description: "Complex industrial piping system installation",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934866/IMG-20250429-WA0005_prk4vz.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 37,
        title: "Pipe Systems Installation",
        description: "Demonstration of precision extinguishers",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934865/IMG-20250429-WA0000_fkgdxi.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 38,
        title: "Fabrication of Fire Suppression System",
        description: "Fire suppression pipes installation process",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934866/IMG-20250429-WA0006_x3esrb.jpg",
        type: "image",
        category: "Fabrication",
    },
    {
        id: 39,
        title: "Industrial Piping",
        description: "Complex industrial piping system installation",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934868/IMG-20250429-WA0017_xptlve.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    // You can add more items as needed
    {
        id: 40,
        title: "Emergency Systems",
        description: "Bulk Fire Extinguisher Cylinders Available",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934868/IMG-20250429-WA0014_cj4wku.jpg",
        type: "image",
        category: "Fire Extinguisher",
    },
    {
        id: 41,
        title: "Fire emergency response",
        description: "Fire Extinguisher Cylinders",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934867/IMG-20250429-WA0009_che3l6.jpg",
        type: "image",
        category: "Fire Extinguisher",
    },
    {
        id: 42,
        title: "Underground Pipe Installation",
        description: "Underground pipe installation and outlet",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934866/IMG-20250429-WA0007_fu0jch.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 43,
        title: "Joints Welding",
        description: "Bolting together FM200 nozzle and pipe system",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934875/IMG-20250429-WA0047_wjgvsi.jpg",
        type: "image",
        category: "Welding",
    },
    {
        id: 44,
        title: "Inspection of FM200 Pipe Systems",
        description: "Custom metal work for pipe systems",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934874/IMG-20250429-WA0043_izftrz.jpg",
        type: "image",
        category: "Welding",
    },
    {
        id: 45,
        title: "Pressure Testing FM200 Fire Suppression System",
        //  omolayo awoyinka ewaoluwa oluwatoyosi oluwaferanmijuomogbogboarayelo
        description: "Pressure testing FM200 pipe system with nitrogen gas",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934874/IMG-20250429-WA0041_h9wjw7.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 46,
        title: "Industrial Piping",
        description: "Complex industrial piping system installation",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934866/IMG-20250429-WA0005_prk4vz.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 47,
        title: "Pipe Systems Installation",
        description: "Demonstration of precision extinguishers",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934865/IMG-20250429-WA0000_fkgdxi.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    {
        id: 48,
        title: "Fabrication of Fire Suppression System",
        description: "Fire suppression pipes installation process",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934866/IMG-20250429-WA0006_x3esrb.jpg",
        type: "image",
        category: "Fabrication",
    },
    {
        id: 49,
        title: "Industrial Piping",
        description: "Complex industrial piping system installation",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934868/IMG-20250429-WA0017_xptlve.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
    // You can add more items as needed
    {
        id: 50,
        title: "Welding FM200 Flange",
        description: "Welding FM200 flange to pipe system",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745938989/IMG_20250206_100941_mcwb0v.jpg",
        type: "image",
        category: "FM200 Installation",
    },
    {
        id: 51,
        title: "Industrial Piping",
        description: "Complex industrial piping system installation",
        source: "https://res.cloudinary.com/dn52re1os/image/upload/v1745934868/IMG-20250429-WA0015_ob3x9h.jpg",
        type: "image",
        category: "Piping and Fitting",
    },
];

// Helper function to get all unique categories
export const getAllCategories = (): string[] => {
    return ["all", ...new Set(mediaItems.map((media) => media.category))];
};